version: "3.9"

services:

  redis:
    container_name: crispy_notes_redis
    image: redis
    restart: always
    ports:
      - "6379:6379"

  backend:
    container_name: crispy_notes_backend
    build: .
    command: sh -c "cd core/ && python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic --noinput && gunicorn core.wsgi --bind 0.0.0.0:8000"
    expose:
      - "8000"
    restart: always
    volumes:
      - .:/app/
      - static_volume:/app/core/static
      - media_volume:/app/core/media
    depends_on:
      - redis

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - redis
      - backend
    restart: always
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/home/app/static
      - media_volume:/home/app/media

  celery_worker:
    build: .
    container_name: crispy_notes_celery_worker
    command: sh -c "cd core/ && celery -A core worker --loglevel=info"
    depends_on:
      - redis
      - backend
    volumes:
      - .:/app/

  celery_beat:
    build: .
    container_name: crispy_notes_celery_beat
    command: sh -c "cd core/ && celery -A core  beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler"
    depends_on:
      - redis
      - backend
    volumes:
      - .:/app/


volumes:
  static_volume:
  media_volume:
