# Generated by Django 3.2.16 on 2022-10-19 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_auto_20221019_0910"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="category",
        ),
        migrations.AddField(
            model_name="post",
            name="category",
            field=models.ManyToManyField(to="blog.Category"),
        ),
    ]
